# golangci-lint configuration for cool-kit
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

# output:
#   format: colored-line-number
#   print-issued-lines: true
#   print-linter-name: true
#   sort-results: true

linters:
  enable:
    # Error handling
    - errcheck
    - errname
    
    # Code style
    - govet
    - gofmt
    - goimports
    - misspell
    - unconvert
    
    # Security
    - gosec
    
    # Performance
    - prealloc
    
    # Bugs
    - staticcheck
    - ineffassign
    
    # Complexity
    - gocyclo
    - gocognit
    
    # Code quality
    - gocritic
    - revive
    - unused

  disable:
    - depguard  # We don't need import allowlists

  # v2: Settings are under 'settings' key
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io.Copy
        - (io.Closer).Close

    gocyclo:
      min-complexity: 20

    gocognit:
      min-complexity: 30

    gocritic:
      disabled-checks:
        - hugeParam  # We pass some larger structs around

    gosec:
      excludes:
        - G104  # Audit errors not checked (we use errcheck)
        - G304  # Potential file inclusion via variable (needed for config files)

    misspell:
      locale: US

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else

  # v2: Exclusions are here
  exclusions:
    rules:
      # Exclude some linters from running on tests files
      - path: "_test\\.go"
        linters:
          - gocyclo
          - errcheck
          - gosec
          - gocognit

      # Exclude known issues in generated files
      - path: ".*\\.gen\\.go"
        linters:
          - all

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  new: false
